### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by darkmaterial** [RobertFach/panobot#1]
Hello Robert,
would it be possible to Upload your EAGLE PCB Files?  I would like to remove the Ardunioboard and create a new one with Atmeg256 onboard.

**Comment by RobertFach** [comment]
Hi, 
at the moment I have no 100% opinion about it.
Although everything is open for rebuild, I'm a little bit scared to share the eagle files because of the following reasons:
- It would make it pretty easy for everyone (especially commercial chinese pcb producers) to clone this work and sell the boards. Including all advantages and disadvantages...
- I want to keep control over the hardware because I have several plans with extensions. (The next revision of the board will most probably move to a 32bit core to get some additional processing power.)

Do you have a special use case why you need both combined?

Cheers,

**Comment by darkmaterial** [comment]
Closed, see fork
