### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by ghost** [RobertFach/panobot#9]
I am completly new to the Atom/Platformio enviroment.

And I have a problem with a project from git to compile it.

I am running this on W10

I have installed Atom + Platformio IDE
Also I have installed the command palette and Git(clone) plugin.

This is the project on git: https://github.com/RobertFach/panobot.git

I can prefectly clone this project to my PC, once compiling it Im getting errors’s.
“Error 1” ???

Where can I find the error log?

**Comment by maxgerhardt** [comment]
See https://community.platformio.org/t/compiling-project/6508, this error is caused in the PCINT library https://github.com/neu-rah/PCINT/issues/4#issuecomment-386437836, `warning: narrowing conversion of '-1' from 'int' to 'const uint8_t {aka const unsigned char}' inside { } [-Wnarrowing]` is now considered a compiler error instead of a warning.

**Comment by ghost** [comment]
Many thanks for solving this Max :-)
